modLoader="javafml" #mandatory

loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="GNU GENERAL PUBLIC LICENSE"

[[mods]] #mandatory

modId="corruptedbotany" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Corrupted Botany" #mandatory

logoFile="icon.png" #optional
# A text field displayed in the mod UI
credits="" #optional
# A text field displayed in the mod UI
authors="KunekoDark, Jzells" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Plants invading from a diabolical origin have invaded.
Control The Power Of the Corrupted Botany as it invades your world.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.corruptedbotany]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.corruptedbotany]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
